# Generated by Django 4.0.5 on 2022-12-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_childern_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childern',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
