# Generated by Django 4.0.5 on 2022-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='document',
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default='index.html', max_length=1000),
        ),
    ]
