# Generated by Django 4.0.5 on 2022-12-30 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notice',
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
