# Generated by Django 4.0.5 on 2022-12-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_course_notice_course_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childern',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childern',
            name='progress',
            field=models.CharField(default='PASS', max_length=100),
        ),
    ]
