# Generated by Django 4.0.5 on 2023-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_childern_attendance_childern_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childern',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
