# Generated by Django 4.0.5 on 2023-01-05 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_childern_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childern',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
